### ISSUE TITLE
Enable/Disable K8s

### ISSUE THREAD

**Issue by jjscaria** [smithumble/starship-cockpit#4]
Im using zsh and pwsh on a Mac and I needed to not show K8s info when in pwsh.

Based on https://github.com/smithumble/starship-cockpit/pull/3/files#diff-cb662392a46400debc8e47eb96af768923a239f7606d6c9a70ad1f7049c6bd95 , I tried to do the same for K8s with the following, but it doesnt seem to work. @smithumble Can you please tell me what I am doing wrong?

`${custom.k8s}\`

```toml
[custom.k8s]
command = "starship module kubernetes"
when = '[ "${STARSHIP_COCKPIT_K8S_ENABLED:-true}" = "true" ]'
format = "( $output )"
disabled = false
```

and in the PS Profile

```ps
$Env:STARSHIP_COCKPIT_K8S_ENABLED = 'false'
```
